"""Initial baseline

Revision ID: e0c55ace38e4
Revises: 
Create Date: 2026-04-12 19:50:22.715448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c55ace38e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvers_id'), 'approvers', ['id'], unique=False)
    op.create_index(op.f('ix_approvers_nome'), 'approvers', ['nome'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj_padrao', sa.String(), nullable=True),
    sa.Column('valor_medio', sa.Float(), nullable=False),
    sa.Column('total_documentos', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_nome'), 'providers', ['nome'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo_origem', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_arquivo_origem'), 'documents', ['arquivo_origem'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_arquivo_origem'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_providers_nome'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_approvers_nome'), table_name='approvers')
    op.drop_index(op.f('ix_approvers_id'), table_name='approvers')
    op.drop_table('approvers')
    # ### end Alembic commands ###
